train:
  g: 5
  way: 5
  shot: 5
  pit_mixup_alpha: 3.0
  num_session: 9
  num_base: 55
  num_novel: 45
  num_all: 100
  start_session: 0
  test_times: 100
  seq_sample: false
  tmp_train: true
  stk: false
  model_dir:
    stdu_model_dir: null # for stdu final model
    tmp_model_dir: null # stdu temp model paht
    s0_model_dir: null # session 0's final model path
    sf_model_dir: null # final session's model path
  seed: 0
  epochs:
    epochs_std: 20 # epochs for standard train
    epochs_stdu_base: 2 # epochs for incremental train
    epochs_new: 20 # epochs for incremental session
    epochs_base: 20
    epochs_inc: 1
  lr:
    lr_std: !!float 0.1 # lr for standard train
    lr_stdu_base: !!float 0.0002 # lr for encoder in increment train stage
    lrg: !!float 0.0002  # lr for graph attention
    lr_new: !!float 0.1 # lr for incremental session
    lr_mix_base: !!float 0.1
    lr_inc: !!float 0.0002
    lr_inc2: !!float 0.00001
    

  scheduler: 
    schedule: Step # ['Step', 'Milestone']
    milestones: [40, 80]
    step: 40
    gamma: !!float 0.5
  optimizer:
    decay: !!float 0.0005
    momentum: !!float 0.9
  network:
    temperature: 16
    base_mode: ft_cos  # ['ft_dot', 'ft_cos']
    new_mode: ft_cos  # ['ft_dot', 'ft_cos', 'avg_cos'] ft_dot means using linear classifier, ft_cos means using cosine classifier, avg_cos means using average data embedding and cosine classifier
  strategy:
    data_init: true
    set_no_val: false
    seq_sample: false
  episode:
    train_episode: 50
    episode_way: 5
    episode_shot: 5
    episode_query: 15
    low_way: 5
    low_shot: 5
  dataloader:
    num_workers: 8
    train_batch_size: 128
    test_batch_size: 100
  stdu:
    num_tmpb: 30
    num_tmpi: 25
    num_tmps: 15
    num_incre: 5
    pqa: true
    ap:
      use_ap: true
      ap_type: outer
      ap_on_test: false
    anchor:
      use_anchor: false
      anchor_type: base_anchor
    proto:
      weighted: false
      type: mmt  # ['mmt', 'res']
  extractor:
    sample_rate: 16000
    window_size: 2048
    hop_size: 1024
    mel_bins: 128
    fmin: 0
    fmax: 8000
    window: hann
  episode2:
    train_episode: 50
    episode_way: 20
    base: 10
    syn_new: 5
    episode_shot: 5
    episode_query: 15
    low_way: 5
    low_shot: 5
  



